// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc841.Waffle.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc841.Waffle.Constants;
import org.usfirst.frc841.Waffle.subsystems.*;

/**
 *
 */
public class AutonomousGearStraight extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutonomousGearStraight() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
	    	
    		//Go straight for 1.5s, Power 0.3
    		addSequential (new TimedDriveStraight(1.5, 0.3, true));
	    	
    		//Center and go straight to the Pig
    		addSequential (new DriveTowardsPeg());
    		
    		//Go back 
	    	addSequential (new TimedDriveStraight(0.7, 0.5, false));
	    	
	    	//Turn to the left
	    	addSequential (new TimedTurn(true,0.5,.4));
	    	
	    	//Drive over line
	    	addSequential (new TimedDriveStraight(1.5, 0.5, true));

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
    } 
}
